services:
  mysql:
    image: pablopin92/fintech-mysql:1.0.0
    container_name: fintech-mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: fintech
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  backend:
    image: pablopin92/fintech-backend:1.0.0
    container_name: fintech-backend
    ports:
      - "8000:8000"
    depends_on:
      mysql:
        condition: service_healthy

  frontend:
    image: pablopin92/fintech-frontend:1.0.0
    container_name: fintech-frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mysql_data: