services:
  mysql:
    build:
      context: ./database
      dockerfile: ./Dockerfile
    image: pablopin92/fintech-mysql:latest
    container_name: fintech-mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: fintech
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - fintech-net

  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    image: pablopin92/fintech-backend:latest
    container_name: fintech-backend
    ports:
      - "8000:8000"
    depends_on:
      mysql:
        condition: service_healthy 
    networks:
      - fintech-net

  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    image: pablopin92/fintech-frontend:latest
    container_name: fintech-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - fintech-net

volumes:
  mysql_data:

networks:
  fintech-net:
    driver: bridge